---
title: "Sales Report"
author: "Data Science Consulting"
date: "6/20/2019"
output: 
    html_document:
        code_folding: none
        df_print: paged
        theme: flatly
        highlight: tango
        toc: yes
        toc_depth: 2
        number_sections: yes
    pdf_document:
        toc: yes
        toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    out.width = "100%",
    out.height = "500px",
    fig.pos = "center",
    fig.align = "center",
    dpi = 300)
```

```{r}
interactive <- TRUE
```


```{r libraries}
library(tidyverse)
library(lubridate)
library(tidyquant)
library(plotly)
```

```{r scripts}
source("../00_scripts/plot_sales.R")
```

```{r}
bike_orderlines_tbl <- read_rds("../00_data/bike_sales/data_wrangled/bike_orderlines.rds")
```

# Total Sales Charts {.tabset .tabset-fade .tabset-pills}

## Quarterly Sales Trends

```{r}
plot_total_sales(unit = "quarter", interactive = interactive)
```


## Monthly Sales Trends

```{r}
plot_total_sales(unit = "month", interactive = interactive)
```

## Weekly Sales Trends

```{r}
plot_total_sales(unit = "week", date_format = "%Y-%m-%d", interactive = interactive)
```

# Category Sales Charts {.tabset .tabset-fade .tabset-pills}

## Road {.tabset .tabset-fade}

### Quarterly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Road", unit = "quarter", ncol = 1, interactive = interactive)
```


### Monthly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Road", unit = "month", ncol = 1, interactive = interactive)
```


### Weekly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Road", unit = "week", date_format = "%Y-%m-%d", ncol = 1
                , interactive = interactive)
```


# Category Sales Charts {.tabset .tabset-fade .tabset-pills}

## Mountain {.tabset .tabset-fade}

### Quarterly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Mountain", unit = "quarter", ncol = 1, interactive = interactive)
```


### Monthly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Mountain", unit = "month", ncol = 1, interactive = interactive)
```


### Weekly

```{r, out.height = "1000px"}
plot_categories(category_1 = "Mountain", unit = "week", date_format = "%Y-%m-%d", ncol = 1, interactive = interactive)
```




















